### ISSUE TITLE
New home page

### ISSUE THREAD

**Issue by AltiMario** [eLearningDAO/POCRE#57]
The old home page was partially implemented (there were just problems with responsiveness) and it is still in the source, code but commented on. It refers to this design
https://www.figma.com/file/CqtC9u2rLf0WcpFv44VoQc/Web3-e-learning-(Copy)?node-id=154%3A53
however in these weeks, we updated some components like the logo and background, so make sure you don't overwrite the new things.
We need a new icon home, linked to this homepage
![image](https://user-images.githubusercontent.com/598726/195368780-729b2859-5740-4eb8-bf73-476d0fea11fc.png)
The home will be accessible to everybody (logged and not logged users).
These are the interacting components
![image](https://user-images.githubusercontent.com/598726/195372367-61e5609d-48c0-4e6d-8f38-f49e1a1c7506.png)
We don't have any system yet to define the concept of "trending", temporary it can be just the first 5 creations in the "progress" of the assignment.

**Comment by AltiMario** [comment]
Further clarification.
The page is already partially developed (but commented) and there are probably no APIs implemented for the "list" of content
I need new endpoints for:
- "trending creations" that return the first 5 creations in the "progress" 
- "last creations" that returns the last N (let's say 5) creations fully assigned
- "top authors" that returns the first N (let's say 5) authors with more creations
- "last recognised materials" that returns the last N (let's say 5) materials recognised (not claimed)
In this ticket you can mock the endpoints, waiting that someonelse implement them (in another ticket).
On clicking on every single "box" the endpoints are already developed (working currently). Only the "lists" need implementation.

**Comment by AltiMario** [comment]
Last API updates
1- https://pocre-api.herokuapp.com/v1/creations?is_trending=true will return all open creations that are not in litigation yet. 
2- We can get partially assigned creations with https://pocre-api.herokuapp.com/v1/creations?is_partially_assigned=true and fully assigned with https://pocre-api.herokuapp.com/v1/creations?is_fully_assigned=true. 
3- https://pocre-api.herokuapp.com/v1/users?top_authors=true will return the list of top authors. It also adds a new calculated field total_creations showing the total creations by the user.
4- https://pocre-api.herokuapp.com/v1/materials?is_recognized=true&is_claimed=false will give all recognized materials that are not yet claimed. We can do multiple variations by toggling is_recognized and is_claimed flags.

All of the above changes are done with existing endpoints (no new endpoints were added)

Docs available at
For 1 and 2) https://pocre-api.herokuapp.com/v1/docs/#/Creation/get_creations
3) https://pocre-api.herokuapp.com/v1/docs/#/Users/get_users
4) https://pocre-api.herokuapp.com/v1/docs/#/Material/get_materials

**Comment by AltiMario** [comment]
I found these issues:
- the "trending creation" (carousel) is not fully implemented, the real images should come from the API
- on clicking to "preview" the output page is empty  
![image](https://user-images.githubusercontent.com/598726/197526000-be0389c8-ad24-489f-b009-f3be43e93346.png)
- clicking on the "authors" doesn't go to the related user wallet
- the materials link is not correctly implemented, it sends to an empty page
![image](https://user-images.githubusercontent.com/598726/197526445-59fda8a1-2ee6-4801-9213-13878363a14e.png)

**Comment by AltiMario** [comment]
Don't make the list infinite
![image](https://user-images.githubusercontent.com/598726/198728751-07bcdd39-492b-4d69-8bb3-8215063f80b4.png)

**Comment by AltiMario** [comment]
![image](https://user-images.githubusercontent.com/598726/204673062-647e8240-c107-4d2f-9c24-622f01ab228a.png)

**Comment by UmairMukhtar** [comment]
okay understood

**Comment by AltiMario** [comment]
this link is not necessary
![image](https://user-images.githubusercontent.com/598726/208896209-9cf2d5a0-efc6-47fa-ac7f-60ca202a9423.png)

**Comment by UmairMukhtar** [comment]
Profile images are now coming from real users
![image](https://user-images.githubusercontent.com/34018917/209189124-b7436ff4-d126-49af-8458-be78ebae69c0.png)

**Comment by UmairMukhtar** [comment]
Removed ligitations menu

![image](https://user-images.githubusercontent.com/34018917/209190265-dfad9818-0737-45e9-8a23-71a33b4e19d8.png)

**Comment by UmairMukhtar** [comment]
The images are now being fetched from image materials of top authors

![image](https://user-images.githubusercontent.com/34018917/209476052-209fe9e6-76fe-4e2d-b670-4bed47f66395.png)

**Comment by UmairMukhtar** [comment]
Fixed
![homepage](https://user-images.githubusercontent.com/34018917/209945114-768872ad-bce7-47d0-9303-6ecc07c204d6.PNG)

**Comment by AltiMario** [comment]
this is still missing
![image](https://user-images.githubusercontent.com/598726/209945285-36e1a1e6-ebb4-49b7-987c-d4903125fcf4.png)

**Comment by UmairMukhtar** [comment]
https://github.com/eLearningDAO/POCRE/pull/263 fixed
